services:
    security.authentication.listener.lightsaml_sp:
        class: LightSaml\SpBundle\Security\Firewall\LightSamlSpListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
            - [setProfile, ["@ligthsaml.profile.acs"]]

    security.authentication.provider.lightsaml_sp:
        class: LightSaml\SpBundle\Security\Authentication\Provider\LightsSamlSpAuthenticationProvider
        arguments:
            - ~ # provider key
            - ~ # user provider
            - ~ # force
            - "@security.user_checker"
            - "@lightsaml_sp.username_mapper.simple" # username mapper
            - ~ # user creator
            - ~ # attribute mapper
            - ~ # token factory
        abstract: true

    security.firewall.logout_handler.lightsaml_sp:
        class: LightSaml\SpBundle\Security\Firewall\LightSamlLogoutHandler
        arguments:
            - "@lightsaml.service.binding_factory"
            - "@lightsaml.store.sso_state"
            - "@router"
            - "@lightsaml_sp.slo.message_factory"